Aksw 13145 add featurizer evaluation subpackage to de-image-featurizer
akridata-ai/DE-image-featurizer pull request #12
Opened 2023-01-31 12:49 UTC by rahulthakurakridata

Added the following:
1. Evaluate functionality to compare different image featurizers (TF-HUB ones and also the one present in this repository).
2. Provides training and test accuracy with respect to different number of feature dimensions(using PCA).

2023-02-02 06:34 UTC, sabarish-akridata commented on DE-image-featurizer/evaluate/evaluator.py
> +
Remove empty line after parameters.

2023-02-02 06:34 UTC, sabarish-akridata commented on DE-image-featurizer/evaluate/evaluator.py
> +    >>> fan = ImageFeatureEvaluator(data_dir,'https://tfhub.dev/google/imagenet/mobilenet_v1_025_224/feature_vector/5',32,False)
Create a separate variable for `MODEL_URL` instead of making this line so long.

2023-02-02 06:34 UTC, sabarish-akridata commented on DE-image-featurizer/evaluate/evaluator.py
> +    >>> fan = ImageFeatureEvaluator(data_dir,'https://tfhub.dev/google/imagenet/mobilenet_v1_025_224/feature_vector/5',32,False)
Use a different name than `fan` for the object. Can't relate `fan` to what we are doing here. Call it `evaluator` instead.

2023-02-02 06:34 UTC, sabarish-akridata commented on DE-image-featurizer/evaluate/evaluator.py
> +    featurizer_selected : string
rename to `featurizer`. The `_selected` suffix makes the variable name long without adding much info.
Add some extra info like so:
```
featurizer: string
    Name of a traditional CV featurizer, or URL to a tf-hub featurizer model.
    Accepted values for names are 'hog', 'lbp', 'orb', 'sift', <include other names>
```

2023-02-02 06:34 UTC, sabarish-akridata commented on DE-image-featurizer/evaluate/evaluator.py
> +    structure: boolean
Rename this to `splits`.

2023-02-02 06:34 UTC, sabarish-akridata commented on DE-image-featurizer/evaluate/evaluator.py
> +    >>> featurizer, preprocessor = fan.load_featurizer()
No need to return these and pass them to the next method. Assign these as attributes of the object inside the `load_featurizer` method, and use them in the `extract_features` method.

2023-02-03 13:28 UTC, raghav-akridata requested changes

2023-02-03 13:28 UTC, raghav-akridata commented on DE-image-featurizer/evaluate/evaluator.py
> +import sys
@rahulthakurakridata Please organise and optimise imports. Refer [here](https://www.jetbrains.com/pycharm/guide/tips/optimize-imports/).

2023-02-03 13:28 UTC, raghav-akridata commented on DE-image-featurizer/evaluate/evaluator.py
> +DEF_N_COMPONENTS = [2, 8, 16, 32, 64, 128]  # Different number of components used during PCA.
@rahulthakurakridata Let's follow an uniform comment structure. Comments followed by a code line.

Something like this:
```python
# Different number of components used during PCA.
DEF_N_COMPONENTS = [2, 8, 16, 32, 64, 128]
# The dictionary describing different traditional CV featurizer.
FEATURIZER_DICT = {'hog': HOG(), 'lbp': LBP(), 'orb': ORB(), 'sift': SIFT()}
# Random seed for shuffling and transformations
SEED = 123  
```

2023-02-03 13:28 UTC, raghav-akridata commented on DE-image-featurizer/evaluate/evaluator.py
> +DEF_N_COMPONENTS = [2, 8, 16, 32, 64, 128]  # Different number of components used during PCA.
For very short comments 2-3 words we can still write inline comments. The judgment still lies with you. But keep in mind uniformity increases readability.

2023-02-03 13:28 UTC, raghav-akridata commented on DE-image-featurizer/evaluate/evaluator.py
> +            if features_array is None:
@rahulthakurakridata Try avoiding multiple if-else statements. Maybe, you can append all features to a list and do `np.asarray` over it.

2023-02-03 20:58 UTC, raghav-akridata approved these changes

2023-02-06 04:26 UTC, merged